### ISSUE TITLE
BIG TEXT

### ISSUE THREAD

**Issue by HonzasikCZ** [intexpression/nekito#12]
**Describe the bug**
There is large text everywhere

**To Reproduce**
1. start minecraft

**Expected behavior**
There's big text everywhere...it should be normal size

**Screenshots**
![obrazek](https://github.com/intexpression/nekito/assets/94143975/85094a3e-7b6c-48b7-9487-a86186b41dd0)

**Desktop (please complete the following information):**
 - Windows 10
 - Nekito 1.9

**Additional context**
There is large text everywhere even in clickgui

**Comment by intexpression** [comment]
"IMPORTANT

IF RENDER ISNT WORKING AND IT HAS BUGS
Download [openjdk8](https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u382-b05/OpenJDK8U-jdk_x64_windows_hotspot_8u382b05.msi)

Install it and Change Java executable in your nekito installation (mc launcher or sklauncher) to openjdk with you downloaded. "


 u need glasses
