### ISSUE TITLE
YOu forgot to remove debug shit thats all I want to cum

### ISSUE THREAD

**Issue by WoufLeDieu** [intexpression/nekito#3]
VclipCommand  : final String direction -useless
Same for Hclip
ClickGui - could add directly into the array list (optimize it by almost nothing so you can let it)
MainMenuLoadingScreen remove the useless var

**Comment by intexpression** [comment]
1. debug is for lwjgl 3. and if somebody got an issue with it I have all info abt it.
2. I'm too lazy to delete that small detail.
3. ill probably  fix it in next release 
4. the same as 2.
